Repository Ggwepq/exts, pull requests merged in 2025-03, with the labels that each got.

#1 Add more information on register page and update profile
  app/Livewire/Forms/LoginForm.php
  app/Models/User.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/layout/navigation.blade.php
  resources/views/livewire/pages/auth/register.blade.php
  resources/views/livewire/profile/update-password-form.blade.php
  resources/views/livewire/profile/update-profile-information-form.blade.php
Labels: enhancement

#3 Badging transaction type
  resources/views/livewire/dashboard/containers/left-sidebar.blade.php
  resources/views/livewire/pages/user/transactions.blade.php
Labels: enhancement

#6 Updated Migrations
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2025_03_03_135302_create_account_categories_table.php
  database/migrations/2025_03_08_135502_create_category_groups_table.php
  database/migrations/2025_03_08_135505_create_categories_table.php
  database/migrations/2025_03_08_135508_create_accounts_table.php
  database/migrations/2025_03_08_135512_create_transaction_categories_table.php
  database/migrations/2025_03_08_135516_create_types_table.php
  database/migrations/2025_03_08_135520_create_transactions_table.php
  database/migrations/2025_03_08_135523_create_budgets_table.php
  database/migrations/2025_03_08_135526_create_goals_table.php
  database/migrations/2025_03_08_135529_create_goal_progress_table.php
  database/migrations/2025_03_08_135533_create_transfers_table.php
  database/migrations/2025_03_08_135536_create_recurring_transactions_table.php
  database/migrations/2025_03_08_135539_create_transfer_transactions_table.php
  database/migrations/2025_03_08_140626_create_tags_table.php
  database/migrations/2025_03_08_140629_create_transaction_tags_table.php
  database/migrations/2025_03_08_140631_create_themes_table.php
  database/migrations/2025_03_08_140635_create_currencies_table.php
  database/migrations/2025_03_08_140638_create_backup_settings_table.php
  database/migrations/2025_03_08_140644_create_notification_types_table.php
  database/migrations/2025_03_08_140648_create_settings_table.php
  database/migrations/2025_03_08_140651_create_activities_table.php
  database/migrations/2025_03_08_140656_create_history_table.php
  database/seeders/DatabaseSeeder.php
Labels: bug, enhancement

#7 Database migrations changes and models
  app/Models/Account.php
  app/Models/AccountCategory.php
  app/Models/BackupSetting.php
  app/Models/Budget.php
  app/Models/CategoryGroup.php
  app/Models/Currency.php
  app/Models/Goal.php
  app/Models/GoalProgress.php
  app/Models/History.php
  app/Models/NotificationType.php
  app/Models/Recurring.php
  app/Models/Setting.php
  app/Models/Tag.php
  app/Models/Theme.php
  app/Models/TransactionCategory.php
  app/Models/TransctionTags.php
  app/Models/Transfer.php
  app/Models/TransferTransaction.php
  app/Models/Type.php
  database/factories/UserFactory.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2025_03_03_130000_create_category_groups_table.php
  database/migrations/2025_03_03_135302_create_account_categories_table.php
  database/migrations/2025_03_03_151734_create_accounts_table.php
  database/migrations/2025_03_03_151930_create_category_groups_table.php
  database/migrations/2025_03_03_151940_create_types_table.php
  database/migrations/2025_03_03_151941_create_transaction_categories_table.php
  database/migrations/2025_03_03_151945_create_transactions_table.php
  database/migrations/2025_03_03_152956_create_budgets_table.php
  database/migrations/2025_03_03_152959_create_goals_table.php
  database/migrations/2025_03_03_153003_create_goal_progress_table.php
  database/migrations/2025_03_03_153152_create_transfers_table.php
  database/migrations/2025_03_03_153157_create_recurring_transactions_table.php
  database/migrations/2025_03_03_153200_create_installment_transactions_table.php
  database/migrations/2025_03_03_153204_create_settings_table.php
  database/migrations/2025_03_03_153220_create_history_table.php
  database/migrations/2025_03_08_135505_create_categories_table.php
  database/migrations/2025_03_08_135508_create_accounts_table.php
  database/migrations/2025_03_08_135512_create_transaction_categories_table.php
  database/migrations/2025_03_08_135516_create_types_table.php
  database/migrations/2025_03_08_135520_create_transactions_table.php
  database/migrations/2025_03_08_135529_create_goal_progress_table.php
  database/migrations/2025_03_08_135533_create_transfers_table.php
  database/migrations/2025_03_08_135539_create_transfer_transactions_table.php
  database/migrations/2025_03_08_140626_create_tags_table.php
  database/migrations/2025_03_08_140629_create_transaction_tags_table.php
  database/migrations/2025_03_08_140631_create_themes_table.php
  database/migrations/2025_03_08_140635_create_currencies_table.php
  database/migrations/2025_03_08_140638_create_backup_settings_table.php
  database/migrations/2025_03_08_140644_create_notification_types_table.php
  database/migrations/2025_03_08_140648_create_settings_table.php
  database/migrations/2025_03_08_140651_create_activities_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#10 feat(ETS-1): email verification for new user
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  public/img/email-sent.png
  resources/views/livewire/pages/auth/register.blade.php
  resources/views/livewire/pages/auth/verify-email.blade.php
Labels: enhancement

#14 feat(ETS-81) - Add transaction summary
  .github/workflows/preview.yaml
  app/Models/Transaction.php
  resources/views/livewire/pages/user/components/right-sidebar.blade.php
  resources/views/livewire/pages/user/dashboard.blade.php
  resources/views/livewire/pages/user/transactions.blade.php
  resources/views/livewire/pages/user/transactions/list-transaction.blade.php
  routes/web.php
Labels: enhancement

#15 Feat(ETS-7, ETS-6): New Account Page
  .github/workflows/preview.yaml
  app/Models/Account.php
  app/Models/AccountCategory.php
  app/Models/CategoryGroup.php
  app/Models/User.php
  database/migrations/2025_03_03_130000_create_category_groups_table.php
  database/migrations/2025_03_03_151734_create_accounts_table.php
  database/migrations/2025_03_03_151945_create_transactions_table.php
  database/seeders/DatabaseSeeder.php
  resources/views/app.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/dashboard/containers/header.blade.php
  resources/views/livewire/dashboard/dashboard.blade.php
  resources/views/livewire/pages/user/accounts/add.blade.php
  resources/views/livewire/pages/user/accounts/header.blade.php
  resources/views/livewire/pages/user/accounts/index.blade.php
  resources/views/livewire/pages/user/components/right-sidebar.blade.php
  resources/views/livewire/pages/user/components/sidebar-button.blade.php
  resources/views/livewire/pages/user/containers/details-sidebar.blade.php
  resources/views/livewire/pages/user/containers/main-header.blade.php
  resources/views/livewire/pages/user/containers/sidebar.blade.php
  resources/views/livewire/pages/user/dashboard/header.blade.php
  resources/views/livewire/pages/user/dashboard/index.blade.php
  resources/views/livewire/pages/user/transactions.blade.php
  resources/views/livewire/pages/user/transactions/add.blade.php
  resources/views/livewire/pages/user/transactions/header.blade.php
  resources/views/livewire/pages/user/transactions/index.blade.php
  resources/views/livewire/pages/user/transactions/list-transaction.blade.php
  routes/web.php
  vercel.json
Labels: enhancement, fix

#18 Account Page Fixes (ETS-6, ETS-7)
  public/img/default-img.png
  resources/views/livewire/pages/user/accounts/add.blade.php
  resources/views/livewire/pages/user/accounts/index.blade.php
  resources/views/livewire/pages/user/components/placeholders/placeholder.blade.php
  resources/views/livewire/pages/user/containers/sidebar.blade.php
  resources/views/livewire/pages/user/transactions/index.blade.php
Labels: fix

#25 feat: user profile changes
  app/Models/User.php
  config/filesystems.php
  public/.gitignore
  public/app/.gitignore
  public/img/user-img.jpg
  resources/views/components/danger-button.blade.php
  resources/views/livewire/pages/auth/forgot-password.blade.php
  resources/views/livewire/pages/auth/login.blade.php
  resources/views/livewire/pages/auth/register.blade.php
  resources/views/livewire/pages/user/containers/sidebar.blade.php
  resources/views/livewire/pages/user/transactions/add.blade.php
  resources/views/livewire/pages/user/transactions/index.blade.php
  resources/views/livewire/profile/delete-user-form.blade.php
  resources/views/livewire/profile/update-password-form.blade.php
  resources/views/livewire/profile/update-profile-information-form.blade.php
  resources/views/profile.blade.php
  routes/web.php
Labels: enhancement

#26 fix account related bugs
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/livewire/pages/user/accounts/add.blade.php
  resources/views/livewire/pages/user/transactions/add.blade.php
  resources/views/livewire/pages/user/transactions/index.blade.php
Labels: fix

#27 feat: details-sidebar and navbar improvements
  resources/views/layouts/app.blade.php
  resources/views/livewire/pages/user/accounts/add.blade.php
  resources/views/livewire/pages/user/accounts/header.blade.php
  resources/views/livewire/pages/user/accounts/index.blade.php
  resources/views/livewire/pages/user/components/placeholders/details-placeholder.blade.php
  resources/views/livewire/pages/user/containers/details-sidebar.blade.php
  resources/views/livewire/pages/user/containers/main-header.blade.php
  resources/views/livewire/pages/user/containers/sidebar.blade.php
  resources/views/livewire/pages/user/dashboard/index.blade.php
  resources/views/livewire/pages/user/transactions/add.blade.php
  resources/views/livewire/pages/user/transactions/header.blade.php
  resources/views/livewire/pages/user/transactions/index.blade.php
Labels: enhancement

#33 fix: incorrect amount on dashboard (ETS-16)
  resources/views/livewire/pages/user/dashboard/index.blade.php
Labels: fix

#32 fix: account balance update upon deletion
  app/Livewire/Actions/User/Balance.php
  resources/views/livewire/pages/user/accounts/add.blade.php
  resources/views/livewire/pages/user/accounts/index.blade.php
  resources/views/livewire/pages/user/dashboard/index.blade.php
  resources/views/livewire/pages/user/transactions/edit.blade.php
Labels: fix

#35 ETS-8: edit account details
  resources/views/livewire/pages/user/accounts/edit.blade.php
Labels: enhancement

#36 ETS-9: delete account details
  resources/views/livewire/pages/user/accounts/edit.blade.php
Labels: enhancement

#34 feat(ETS-5): view account details
  resources/views/livewire/pages/user/accounts/edit.blade.php
  resources/views/livewire/pages/user/accounts/index.blade.php
Labels: enhancement

#38 Fix: Remove Apply Button and Hide Sidebar When Image Viewer is Open
  header.blade.php
  resources/views/components/image-viewer.blade.php
  resources/views/livewire/pages/user/transactions/app.css
Labels: fix
